version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: cep_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user
      POSTGRES_DB: cepdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: api_cep
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=cepdb;Username=postgres;Password=user"
      ViaCep__BaseUrl: "https://viacep.com.br/ws/"
    depends_on:
      - postgres

volumes:
  pgdata:
